export const CREATE_CATEGORY_USECASE = 'CREATE_CATEGORY_USECASE';
export const UPDATE_CATEGORY_USECASE = 'UPDATE_CATEGORY_USECASE';
export const CREATE_CATEGORY_SERVICE = 'CREATE_CATEGORY_SERVICE';
export const UPDATE_CATEGORY_SERVICE = 'UPDATE_CATEGORY_SERVICE';
export const FIND_ALL_CATEGORY_SERVICE = 'FIND_ALL_CATEGORY_SERVICE';
export const FIND_BY_ID_CATEGORY_SERVICE = 'FIND_BY_ID_CATEGORY_SERVICE';
export const FIND_ALL_CATEGORY_USECASE = 'FIND_ALL_CATEGORY_USECASE';
